name: prsvm-ml-backend-tests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'ml-backend/data/**'
      - 'ml-backend/models/**'
      - 'ml-backend/tests/**'
jobs:
  model_test:
    runs-on: ubuntu-latest
    container: dvcorg/cml:latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-dvc@v1
        with:
          version: '3.19.0'
      - name: Model Test
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.ORIGINAL_SERVICE_ACCOUNT_JSON }}
        run: |
          git config --global --add safe.directory '*'

          apt-get update && apt-get install libgl1
          pip install -r test_requirements.txt

          dvc pull

          unzip -o ml-backend/data/data.zip -d ml-backend/data/

          dvc repro
          git fetch --prune
          echo '## Model Test' >> report.md
          dvc metrics diff --md >> report.md
          echo '## Examples' >> report.md
          echo '![](./example_0.png "Example #1")' >> report.md
          echo '![](./example_1.png "Example #2")' >> report.md

          cml comment create report.md
